/* Each stage owns its renderer and actions. Register future stages in STAGES. */
const STORAGE_KEY='binary-explorer-v1';
const freshActivity=()=>({bulbs:[0,0,0,0,0],seenOn:false,seenOff:false,phase:'explore',message:''});
let state={screen:'welcome',student:{school:'',name:''},activity:freshActivity(),stage2:freshStage2(),stage3:freshStage3(),stage4:freshStage4(),stage5:freshStage5(),stage6:freshStage6(),lastStage:'stage1'};
try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved?.version===1&&typeof saved.student?.school==='string'&&typeof saved.student?.name==='string'){state.student={school:saved.student.school.slice(0,60),name:Array.from(saved.student.name).slice(0,5).join('')};const a=saved.activity;if(a&&Array.isArray(a.bulbs)&&a.bulbs.length===5&&a.bulbs.every(v=>v===0||v===1)&&['explore','summary','mission','success','complete'].includes(a.phase)){state.activity={...freshActivity(),...a,seenOn:!!a.seenOn,seenOff:!!a.seenOff};}const second=saved.stage2;if(second&&Array.isArray(second.bulbs)&&second.bulbs.length===5&&second.bulbs.every(v=>v===0||v===1)&&['explore','rule','summary','mission','success','complete'].includes(second.phase)){state.stage2={bulbs:second.bulbs,phase:second.phase,touches:Number.isFinite(second.touches)?Math.max(0,second.touches):0,ruleSeen:!!second.ruleSeen};}state.stage3=restoreStage3(saved.stage3);state.stage4=restoreStage4(saved.stage4);state.stage5=restoreStage5(saved.stage5);state.stage6=restoreStage6(saved.stage6);const allowed=screen=>screen==='stage6'&&state.activity.phase==='complete'&&state.stage2.phase==='complete'&&state.stage3.phase==='complete'&&state.stage4.phase==='complete'&&state.stage5.phase==='complete'?'stage6':screen==='stage5'&&state.activity.phase==='complete'&&state.stage2.phase==='complete'&&state.stage3.phase==='complete'&&state.stage4.phase==='complete'?'stage5':screen==='stage4'&&state.activity.phase==='complete'&&state.stage2.phase==='complete'&&state.stage3.phase==='complete'?'stage4':screen==='stage3'&&state.activity.phase==='complete'&&state.stage2.phase==='complete'?'stage3':screen==='stage2'&&state.activity.phase==='complete'?'stage2':'stage1';state.lastStage=allowed(saved.lastStage);if(['stage1','stage2','stage3','stage4','stage5','stage6'].includes(saved.screen)&&state.student.school.trim()&&state.student.name.trim())state.screen=allowed(saved.screen);}}catch{}
const app=document.querySelector('#app');
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({version:1,...state}));}catch{document.querySelector('#announcement').textContent='이 브라우저에서는 저장할 수 없지만 활동은 계속할 수 있어요.';}}
function announce(text){document.querySelector('#announcement').textContent=text;}
function header(){return `<header><div class="brand"><span class="logo">01</span><span>이진수 탐험대</span></div>${state.screen!=='welcome'?`<div class="profile"><span>${escapeHTML(state.student.school)} · <b>${escapeHTML(state.student.name)}</b></span><button class="text-button" data-action="home">처음 화면</button></div>`:'<span class="muted" style="font-size:14px">컴퓨터 과학 첫걸음</span>'}</header>`;}
function welcome(){return `${header()}<main class="welcome"><section class="intro"><div class="eyebrow">BINARY EXPLORERS</div><h1><small>컴퓨터가 이해하는 세상</small><span class="accent">0과 1,</span><br>이진수 탐험대</h1><p>전구를 켜고 끄며<br>컴퓨터의 언어를 알아보자!</p><div class="sample" aria-hidden="true"><div class="sample-item off"><span class="icon">💡</span><span class="display">0</span></div><div class="sample-item"><span class="icon">💡</span><span class="display">1</span></div><div class="sample-item off"><span class="icon">💡</span><span class="display">0</span></div></div></section><form class="form-card" id="start-form"><h2>반가워요, 탐험대원!</h2><p>탐험을 시작하기 전에 나를 소개해요.</p><label for="school">학교 이름</label><input id="school" name="school" autocomplete="organization" maxlength="60" placeholder="예: 광주양동초등학교" value="${escapeHTML(state.student.school)}" required><label for="student-name">나의 이름</label><input id="student-name" name="name" autocomplete="given-name" maxlength="5" placeholder="예: 최우현" value="${escapeHTML(state.student.name)}" required><p class="input-caption">이름은 5글자까지 입력할 수 있어요.</p><button class="primary" id="start" ${state.student.school.trim()&&state.student.name.trim()?'':'disabled'}>이진수 탐험 시작하기</button></form></main><footer class="footnote">학교와 이름은 이 기기의 브라우저에만 저장돼요.</footer>`;}
function bulbs(){return state.activity.bulbs.map((v,i)=>`<button class="bulb ${v?'on':''}" data-bulb="${i}" aria-label="${i+1}번째 전구, ${v?'켜짐, 1':'꺼짐, 0'}" aria-pressed="${!!v}"><span class="icon" aria-hidden="true">💡</span><span class="number" aria-hidden="true">${v}</span></button>`).join('');}
function progress(step=1){return '<div class="progress-row"><span class="step-badge">'+step+'단계 / 6단계</span><span class="steps" aria-hidden="true">'+Array.from({length:6},(_,i)=>'<i style="background:'+(i<step?'#40a9db':'#d6e4ed')+'"></i>').join('')+'</span></div>';}
function stage1(){const a=state.activity;if(a.phase==='complete')return complete();return `${header()}<main class="lesson">${progress()}<div class="lesson-title"><h1>💡 전구를 켜고 꺼 봐!</h1><p>컴퓨터는 두 가지 상태를 구별할 수 있어요.<br>아래 전구를 직접 눌러 보세요.</p></div>${a.phase==='mission'||a.phase==='success'?'<section class="mission"><div><h2>미션 · 똑같이 만들어 보세요!</h2><p>전구를 아래 모양과 똑같이 만들어 보세요!</p></div><div class="target" aria-label="목표: 켜짐, 꺼짐, 켜짐, 꺼짐, 켜짐"><span>💡</span><span class="dim">💡</span><span>💡</span><span class="dim">💡</span><span>💡</span></div></section>':''}<section class="lab" aria-label="전구 실험실"><div class="lab-heading"><p>${escapeHTML(state.student.name)} 학생, 전구를 눌러 볼까요?</p><span class="pill">톡! 누르면 바뀌어요</span></div><div class="bulbs">${bulbs()}</div><p class="touch-hint">전구를 한 번 더 누르면 다시 꺼져요.</p></section><div class="discovery" role="status">${discovery()}</div><div class="lesson-bottom"><span class="muted">${a.phase==='mission'?'모양을 완성하면 다음으로 갈 수 있어요.':'마음껏 눌러 보고, 변화를 찾아보세요.'}</span><button class="primary" disabled>2단계로 이동 →</button></div></main>${a.phase==='summary'?summary():a.phase==='success'?success():''}`;}
function discovery(){const a=state.activity;if(a.phase==='mission')return '<strong>👀 모양을 잘 살펴보세요!</strong><p>켜진 전구와 꺼진 전구를 맞춰 봐요.</p>';if(a.message==='off')return '<strong>🔍 또 하나 발견!</strong><p>전구가 꺼지면 → <b>0</b></p>';if(a.message==='on')return '<strong>💡 발견!</strong><p>전구가 켜지면 → <b>1</b></p>';return '<strong>어떤 일이 일어날까요?</strong><p>아무 전구나 톡 눌러 보세요.</p>';}
function modal(content){return `<div class="overlay"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabindex="-1">${content}</section></div>`;}
function summary(){return modal('<p class="eyebrow">두 가지 규칙을 발견했어요!</p><h2 id="dialog-title">컴퓨터가 사용하는 두 가지 상태</h2><div class="rules"><div class="rule"><span class="icon" aria-hidden="true">💡</span>켜짐 ON = 1</div><div class="rule off"><span class="icon" aria-hidden="true">💡</span>꺼짐 OFF = 0</div></div><p class="lead">컴퓨터는 이렇게 두 가지 상태를<br><b>0과 1로 나타낼 수 있어요!</b></p><button class="primary" data-action="mission">알겠어요! 미션 도전하기</button>');}
function success(){return modal('<div style="font-size:64px" aria-hidden="true">🎉</div><h2 id="dialog-title">성공!</h2><p class="lead">켜진 전구는 <b>1</b>, 꺼진 전구는 <b>0</b>이에요!</p><button class="primary" data-action="complete">1단계 완료하기 ⭐</button>');}
function complete(){return `${header()}<main class="lesson">${progress()}<section class="complete"><div style="font-size:56px" aria-hidden="true">⭐</div><h1>1단계 완료!</h1><h2>컴퓨터가 좋아하는 숫자는?</h2><div class="big-choice"><button data-action="zero" aria-label="0, 꺼짐">0</button><button data-action="one" aria-label="1, 켜짐">1</button></div><p id="choice-feedback" role="status">컴퓨터는 <b>0과 1</b>을 이용해 정보를 나타낼 수 있어요.</p><button class="primary" data-action="next">2단계로 이동 →</button><p class="teaser">그런데 전구마다 값이 다르다고?</p><button class="text-button again" data-action="again">1단계 다시 해 보기</button></section></main>`;}
const STAGES={stage1,stage2,stage3,stage4,stage5,stage6};
function render(){app.innerHTML=state.screen==='welcome'?welcome():STAGES[state.screen]();decorateStage();installBulbMath();const dialog=app.querySelector('.dialog');if(dialog){app.querySelector('main').inert=true;app.querySelector('header').inert=true;dialog.focus();}if(state.screen==='welcome')bindForm();if(state.screen==='stage6')bindBirthdayForm();}
function bindForm(){const form=document.querySelector('#start-form');form.addEventListener('input',()=>{document.querySelector('#start').disabled=!form.elements.namedItem('school').value.trim()||!form.elements.namedItem('name').value.trim();});form.addEventListener('submit',e=>{e.preventDefault();const school=form.elements.namedItem('school').value.trim(),name=Array.from(form.elements.namedItem('name').value.trim()).slice(0,5).join('');if(!school||!name)return;const same=school===state.student.school&&name===state.student.name;state.student={school,name};if(!same){state.activity=freshActivity();state.stage2=freshStage2();state.stage3=freshStage3();state.stage4=freshStage4();state.stage5=freshStage5();state.stage6=freshStage6();state.lastStage='stage1';}state.screen=state.lastStage;save();render();window.scrollTo(0,0);});}
let discoveryTimer;
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.guideAction==='previous'){previousStage();return;}if(state.screen==='stage6'&&handleBirthdayButton(b))return;if(state.screen==='stage5'&&handleChallengeButton(b))return;if(state.screen==='stage4'&&handleMakingButton(b))return;if(state.screen==='stage3'&&handleReadingButton(b))return;if(b.hasAttribute('data-weighted')){toggleWeighted(Number(b.dataset.weighted));return;}if(state.screen==='stage2'&&stage2Action(b.dataset.action))return;if(b.hasAttribute('data-bulb')){toggleBulb(Number(b.dataset.bulb));return;}switch(b.dataset.action){case'home':clearTimeout(discoveryTimer);state.lastStage=state.screen;state.screen='welcome';save();render();break;case'mission':state.activity.phase='mission';state.activity.bulbs=[0,0,0,0,0];save();render();break;case'complete':state.activity.phase='complete';save();render();break;case'again':state.activity=freshActivity();save();render();break;case'zero':document.querySelector('#choice-feedback').textContent='0은 꺼짐! 컴퓨터는 0과 1을 모두 사용해요.';break;case'one':document.querySelector('#choice-feedback').textContent='1은 켜짐! 컴퓨터는 0과 1을 모두 사용해요.';break;case'next':if(state.activity.phase!=='complete')return;state.screen='stage2';state.lastStage='stage2';save();render();window.scrollTo(0,0);break;case'close':render();document.querySelector('[data-action="next"]').focus();break;}});
function toggleBulb(i){const a=state.activity;if(!['explore','mission'].includes(a.phase))return;a.bulbs[i]=1-a.bulbs[i];if(a.phase==='explore'){if(a.bulbs[i]){a.seenOn=true;a.message='on';}else{a.seenOff=true;a.message='off';}}const b=app.querySelector(`[data-bulb="${i}"]`);b.classList.toggle('on',!!a.bulbs[i]);b.classList.remove('popped');void b.offsetWidth;b.classList.add('popped');b.setAttribute('aria-pressed',!!a.bulbs[i]);b.setAttribute('aria-label',`${i+1}번째 전구, ${a.bulbs[i]?'켜짐, 1':'꺼짐, 0'}`);b.querySelector('.number').textContent=a.bulbs[i];app.querySelector('.discovery').innerHTML=discovery();if(a.phase==='explore'&&a.seenOn&&a.seenOff){clearTimeout(discoveryTimer);discoveryTimer=setTimeout(()=>{if(state.screen==='stage1'&&a.phase==='explore'){a.phase='summary';save();render();}},1400);}if(a.phase==='mission'&&a.bulbs.join('')==='10101'){a.phase='success';save();render();celebrate();announce('성공! 켜진 전구는 1, 꺼진 전구는 0이에요!');}save();}
function celebrate(){const layer=document.createElement('div');layer.className='confetti';layer.setAttribute('aria-hidden','true');for(let i=0;i<40;i++){const bit=document.createElement('i');bit.style.left=`${Math.random()*100}%`;bit.style.background=['#ffda58','#50b8e8','#fb8fa0'][i%3];bit.style.animationDelay=`${Math.random()*.6}s`;layer.append(bit);}document.body.append(layer);setTimeout(()=>layer.remove(),2800);}
document.addEventListener('keydown',e=>{const dialog=document.querySelector('.dialog');if(!dialog||e.key!=='Tab')return;const controls=[...dialog.querySelectorAll('button,input,[tabindex="0"]')];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===dialog)){e.preventDefault();first.focus();}});
render();
if(state.screen==='stage1'&&state.activity.phase==='explore'&&state.activity.seenOn&&state.activity.seenOff){state.activity.phase='summary';save();render();}


